/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DebugMatchRouteImport } from './routes/debug.match'
import { Route as DebugDribbleRouteImport } from './routes/debug.dribble'
import { Route as AppTransfersRouteImport } from './routes/_app.transfers'
import { Route as AppTableRouteImport } from './routes/_app.table'
import { Route as AppSquadRouteImport } from './routes/_app.squad'
import { Route as AppScoutingRouteImport } from './routes/_app.scouting'
import { Route as AppScheduleRouteImport } from './routes/_app.schedule'
import { Route as AppPlayerSearchRouteImport } from './routes/_app.player-search'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppTransfersIndexRouteImport } from './routes/_app.transfers.index'
import { Route as AppPlayerPlayerIdRouteImport } from './routes/_app.player.$playerId'
import { Route as AppMatchTeamSelectionRouteImport } from './routes/_app.match.team-selection'
import { Route as AppMatchResultRouteImport } from './routes/_app.match.result'
import { Route as AppTransfersNegotiatePlayerIdRouteImport } from './routes/_app.transfers.negotiate.$playerId'

const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DebugMatchRoute = DebugMatchRouteImport.update({
  id: '/debug/match',
  path: '/debug/match',
  getParentRoute: () => rootRouteImport,
} as any)
const DebugDribbleRoute = DebugDribbleRouteImport.update({
  id: '/debug/dribble',
  path: '/debug/dribble',
  getParentRoute: () => rootRouteImport,
} as any)
const AppTransfersRoute = AppTransfersRouteImport.update({
  id: '/transfers',
  path: '/transfers',
  getParentRoute: () => AppRoute,
} as any)
const AppTableRoute = AppTableRouteImport.update({
  id: '/table',
  path: '/table',
  getParentRoute: () => AppRoute,
} as any)
const AppSquadRoute = AppSquadRouteImport.update({
  id: '/squad',
  path: '/squad',
  getParentRoute: () => AppRoute,
} as any)
const AppScoutingRoute = AppScoutingRouteImport.update({
  id: '/scouting',
  path: '/scouting',
  getParentRoute: () => AppRoute,
} as any)
const AppScheduleRoute = AppScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => AppRoute,
} as any)
const AppPlayerSearchRoute = AppPlayerSearchRouteImport.update({
  id: '/player-search',
  path: '/player-search',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppTransfersIndexRoute = AppTransfersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppTransfersRoute,
} as any)
const AppPlayerPlayerIdRoute = AppPlayerPlayerIdRouteImport.update({
  id: '/player/$playerId',
  path: '/player/$playerId',
  getParentRoute: () => AppRoute,
} as any)
const AppMatchTeamSelectionRoute = AppMatchTeamSelectionRouteImport.update({
  id: '/match/team-selection',
  path: '/match/team-selection',
  getParentRoute: () => AppRoute,
} as any)
const AppMatchResultRoute = AppMatchResultRouteImport.update({
  id: '/match/result',
  path: '/match/result',
  getParentRoute: () => AppRoute,
} as any)
const AppTransfersNegotiatePlayerIdRoute =
  AppTransfersNegotiatePlayerIdRouteImport.update({
    id: '/negotiate/$playerId',
    path: '/negotiate/$playerId',
    getParentRoute: () => AppTransfersRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/setup': typeof SetupRoute
  '/dashboard': typeof AppDashboardRoute
  '/player-search': typeof AppPlayerSearchRoute
  '/schedule': typeof AppScheduleRoute
  '/scouting': typeof AppScoutingRoute
  '/squad': typeof AppSquadRoute
  '/table': typeof AppTableRoute
  '/transfers': typeof AppTransfersRouteWithChildren
  '/debug/dribble': typeof DebugDribbleRoute
  '/debug/match': typeof DebugMatchRoute
  '/match/result': typeof AppMatchResultRoute
  '/match/team-selection': typeof AppMatchTeamSelectionRoute
  '/player/$playerId': typeof AppPlayerPlayerIdRoute
  '/transfers/': typeof AppTransfersIndexRoute
  '/transfers/negotiate/$playerId': typeof AppTransfersNegotiatePlayerIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/setup': typeof SetupRoute
  '/dashboard': typeof AppDashboardRoute
  '/player-search': typeof AppPlayerSearchRoute
  '/schedule': typeof AppScheduleRoute
  '/scouting': typeof AppScoutingRoute
  '/squad': typeof AppSquadRoute
  '/table': typeof AppTableRoute
  '/debug/dribble': typeof DebugDribbleRoute
  '/debug/match': typeof DebugMatchRoute
  '/match/result': typeof AppMatchResultRoute
  '/match/team-selection': typeof AppMatchTeamSelectionRoute
  '/player/$playerId': typeof AppPlayerPlayerIdRoute
  '/transfers': typeof AppTransfersIndexRoute
  '/transfers/negotiate/$playerId': typeof AppTransfersNegotiatePlayerIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/setup': typeof SetupRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/player-search': typeof AppPlayerSearchRoute
  '/_app/schedule': typeof AppScheduleRoute
  '/_app/scouting': typeof AppScoutingRoute
  '/_app/squad': typeof AppSquadRoute
  '/_app/table': typeof AppTableRoute
  '/_app/transfers': typeof AppTransfersRouteWithChildren
  '/debug/dribble': typeof DebugDribbleRoute
  '/debug/match': typeof DebugMatchRoute
  '/_app/match/result': typeof AppMatchResultRoute
  '/_app/match/team-selection': typeof AppMatchTeamSelectionRoute
  '/_app/player/$playerId': typeof AppPlayerPlayerIdRoute
  '/_app/transfers/': typeof AppTransfersIndexRoute
  '/_app/transfers/negotiate/$playerId': typeof AppTransfersNegotiatePlayerIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/setup'
    | '/dashboard'
    | '/player-search'
    | '/schedule'
    | '/scouting'
    | '/squad'
    | '/table'
    | '/transfers'
    | '/debug/dribble'
    | '/debug/match'
    | '/match/result'
    | '/match/team-selection'
    | '/player/$playerId'
    | '/transfers/'
    | '/transfers/negotiate/$playerId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/setup'
    | '/dashboard'
    | '/player-search'
    | '/schedule'
    | '/scouting'
    | '/squad'
    | '/table'
    | '/debug/dribble'
    | '/debug/match'
    | '/match/result'
    | '/match/team-selection'
    | '/player/$playerId'
    | '/transfers'
    | '/transfers/negotiate/$playerId'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/setup'
    | '/_app/dashboard'
    | '/_app/player-search'
    | '/_app/schedule'
    | '/_app/scouting'
    | '/_app/squad'
    | '/_app/table'
    | '/_app/transfers'
    | '/debug/dribble'
    | '/debug/match'
    | '/_app/match/result'
    | '/_app/match/team-selection'
    | '/_app/player/$playerId'
    | '/_app/transfers/'
    | '/_app/transfers/negotiate/$playerId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  SetupRoute: typeof SetupRoute
  DebugDribbleRoute: typeof DebugDribbleRoute
  DebugMatchRoute: typeof DebugMatchRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/debug/match': {
      id: '/debug/match'
      path: '/debug/match'
      fullPath: '/debug/match'
      preLoaderRoute: typeof DebugMatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/debug/dribble': {
      id: '/debug/dribble'
      path: '/debug/dribble'
      fullPath: '/debug/dribble'
      preLoaderRoute: typeof DebugDribbleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/transfers': {
      id: '/_app/transfers'
      path: '/transfers'
      fullPath: '/transfers'
      preLoaderRoute: typeof AppTransfersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/table': {
      id: '/_app/table'
      path: '/table'
      fullPath: '/table'
      preLoaderRoute: typeof AppTableRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/squad': {
      id: '/_app/squad'
      path: '/squad'
      fullPath: '/squad'
      preLoaderRoute: typeof AppSquadRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/scouting': {
      id: '/_app/scouting'
      path: '/scouting'
      fullPath: '/scouting'
      preLoaderRoute: typeof AppScoutingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/schedule': {
      id: '/_app/schedule'
      path: '/schedule'
      fullPath: '/schedule'
      preLoaderRoute: typeof AppScheduleRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/player-search': {
      id: '/_app/player-search'
      path: '/player-search'
      fullPath: '/player-search'
      preLoaderRoute: typeof AppPlayerSearchRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/transfers/': {
      id: '/_app/transfers/'
      path: '/'
      fullPath: '/transfers/'
      preLoaderRoute: typeof AppTransfersIndexRouteImport
      parentRoute: typeof AppTransfersRoute
    }
    '/_app/player/$playerId': {
      id: '/_app/player/$playerId'
      path: '/player/$playerId'
      fullPath: '/player/$playerId'
      preLoaderRoute: typeof AppPlayerPlayerIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/match/team-selection': {
      id: '/_app/match/team-selection'
      path: '/match/team-selection'
      fullPath: '/match/team-selection'
      preLoaderRoute: typeof AppMatchTeamSelectionRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/match/result': {
      id: '/_app/match/result'
      path: '/match/result'
      fullPath: '/match/result'
      preLoaderRoute: typeof AppMatchResultRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/transfers/negotiate/$playerId': {
      id: '/_app/transfers/negotiate/$playerId'
      path: '/negotiate/$playerId'
      fullPath: '/transfers/negotiate/$playerId'
      preLoaderRoute: typeof AppTransfersNegotiatePlayerIdRouteImport
      parentRoute: typeof AppTransfersRoute
    }
  }
}

interface AppTransfersRouteChildren {
  AppTransfersIndexRoute: typeof AppTransfersIndexRoute
  AppTransfersNegotiatePlayerIdRoute: typeof AppTransfersNegotiatePlayerIdRoute
}

const AppTransfersRouteChildren: AppTransfersRouteChildren = {
  AppTransfersIndexRoute: AppTransfersIndexRoute,
  AppTransfersNegotiatePlayerIdRoute: AppTransfersNegotiatePlayerIdRoute,
}

const AppTransfersRouteWithChildren = AppTransfersRoute._addFileChildren(
  AppTransfersRouteChildren,
)

interface AppRouteChildren {
  AppDashboardRoute: typeof AppDashboardRoute
  AppPlayerSearchRoute: typeof AppPlayerSearchRoute
  AppScheduleRoute: typeof AppScheduleRoute
  AppScoutingRoute: typeof AppScoutingRoute
  AppSquadRoute: typeof AppSquadRoute
  AppTableRoute: typeof AppTableRoute
  AppTransfersRoute: typeof AppTransfersRouteWithChildren
  AppMatchResultRoute: typeof AppMatchResultRoute
  AppMatchTeamSelectionRoute: typeof AppMatchTeamSelectionRoute
  AppPlayerPlayerIdRoute: typeof AppPlayerPlayerIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppDashboardRoute: AppDashboardRoute,
  AppPlayerSearchRoute: AppPlayerSearchRoute,
  AppScheduleRoute: AppScheduleRoute,
  AppScoutingRoute: AppScoutingRoute,
  AppSquadRoute: AppSquadRoute,
  AppTableRoute: AppTableRoute,
  AppTransfersRoute: AppTransfersRouteWithChildren,
  AppMatchResultRoute: AppMatchResultRoute,
  AppMatchTeamSelectionRoute: AppMatchTeamSelectionRoute,
  AppPlayerPlayerIdRoute: AppPlayerPlayerIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  SetupRoute: SetupRoute,
  DebugDribbleRoute: DebugDribbleRoute,
  DebugMatchRoute: DebugMatchRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
